zoidyzoidzoid/awesome-ebpf

readme.md

As for other sections, make the remaining parts more like a list.
I have not run the linter, sorry.
Feel free to add one line of introduction to each section if you like, I did not judge it necessary but it depends on what you prefer :)

Follow-up: Rework the rest of the list

---

readme.md

Previous link does not work any more.

Update link for BPF design Q&A

---

readme.md

This is some tutorial about ebpf from oracle
Signed-off-by: Bo YU <tsu.yubo@gmail.com>

Add a series of notes about ebpf from oracle

---

readme.md

As described in the commit logs, first patch moves around some links (but does not add or remove anything). Second commit add a brief BPF description at the top of the document. Then the last two commits add new links to the list.

Rework and expand list

---

LICENSE
package.json
readme.md
yarn.lock

Except false positives about sub lists.
Makes some progress on https://github.com/zoidbergwill/awesome-ebpf/issues/22
GitHub doesn't include CC0 in its license templates, so I used the Unlicense which I think is similar.
Compared to before this PR, there are a lot less awesome-lint errors now. The only errors left are:
- `remark-lint:awesome/github` - says GitHub doesn't pick up the License which I think it will when this is merged into master.
- `remark-lint:awesome/list-item` - about awesome-lint not picking up sub-lists, [upstream issue](https://github.com/sindresorhus/awesome-lint/issues/44)
Before:
```
1 remark-lint:awesome/badge
1 remark-lint:awesome/github
136 remark-lint:awesome/list-item
2 remark-lint:awesome/spell-check
1 remark-lint:awesome/toc
51 …
```

Create LICENSE and fix most awesome-lint errors

---

readme.md

Previous link was broken. Alternative url for the slides : https://web.archive.org/web/20160617030201/https://events.linuxfoundation.org/sites/events/files/slides/bpf_collabsummit_2015feb20.pdf

Update broken link

---

readme.md

Closes https://github.com/zoidbergwill/awesome-ebpf/issues/35

Add ebpf.io

---

readme.md

Link to the official FreeBSD manual about BPF

---

readme.md

I made this example as part of my PhD. I think it's relevant for this repo.

Add eBPF kill example to readme

---

readme.md

I think my paper about eBPF is now good enough to be added as a generic article on this repository. The article gives a simple overview over how to get started with eBPF.

Added eBPF - From a Programmer's Perspective

---

readme.md

This is a walkthrough on how to use C++ and the LLVM libraries to dynamically assemble and load BPF programs at runtime

Add a C++ and LLVM tutorial from Trail of Bits

---

readme.md

Let me know if you have any comments!

Add wachy - userspace eBPF perf debugging tool

---

readme.md

Adding a link to my repo with various talks and their code examples, hope this is of interest!

Add Beginner's Guide to eBPF

---

readme.md

Fixes https://github.com/zoidbergwill/awesome-ebpf/issues/72

add merbridge in Projects Related to eBPF

---

readme.md

`rbperf` is a Ruby profiler and tracer that runs in BPF

Add rbperf

---

readme.md

See https://github.com/eunomia-bpf/eunomia-bpf and https://ebpf.io/applications#eunomia-bpf.

Add eunomia-bpf to eBPF Tools

---

readme.md

Adding ebpfmon to the Tools section of "Projects related to eBPF"

Add ebpfmon to Tools section

---

readme.md

Add the tutorial repo https://github.com/eunomia-bpf/bpf-developer-tutorial

Add bpf-developer-tutorial

---

readme.md

Hi there 👋 , it's [PcapPlusPlus](https://github.com/seladb/PcapPlusPlus) maintainer! We recently added an option to create and work with AF_XDP sockets: https://pcapplusplus.github.io/docs/next/features#af_xdp-support-beta
Please let me know if you'll consider adding PcapPlusPlus to the list of Projects Related to eBPF.

Add PcapPlusPlus to Projects Related to eBPF

---

readme.md

Added [bpfman](https://github.com/bpfman/bpfman) to eBPF tools list

Add bpfman to tools

---

readme.md

docs: add harpoon to the security projects list

---

readme.md

docs: add blog about continuous profiling

---

readme.md

A high performance and lightweight captive portal solution for wireless networks. It leverages eBPF for traffic control and deep packet inspection capabilities, with plans to gradually replace nftables firewall functionality with eBPF-based solutions.
https://github.com/liudf0716/apfree-wifidog

Add ApFree WiFiDog to eBPF Networking Projects

---

readme.md

As per issue #123: added ipx_wrap to "Projects Related to eBPF" > "Networking"

Add ipx_wrap to Networking Projects
